# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    profiles:
        active: dev
        #include: swagger
        include: no-liquibase
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false # we use gulp + BrowserSync for livereload
    jackson:
      serialization.indent_output: true
    sql:
     init:
      mode: always
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/city_data?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: test#123
        hikari:
            maximumPoolSize: 8
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
                pool-name: CityPool
    jpa:
        database: MYSQL
        show-sql: true
        open-in-view: false
        properties:
            hibernate.hbm2ddl.auto: update
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false

    data:
        jest:
            uri: http://localhost:9200

    elasticsearch:
        rest:
            uris: http://localhost:9200
    cache:
        jcache:
            config: classpath:ehcache.xml
    messages:
        cache-duration: 1
    thymeleaf:
        cache: false
        encoding: UTF-8
        mode: HTML
    servlet:
        multipart:
          enabled: true
          file-size-threshold: 0
          max-file-size: 500MB
          max-request-size: 500MB
          resolve-lazily: false

    liquibase:
        contexts: dev
server:
    port: 80
    servlet:
        context-path: /
        session:
          cookie:
            http-only: true
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024